jobs:
  - job: Release
    displayName: "Release Nuget Packages"

    pool:
      vmImage: "Ubuntu 18.04"

    variables:
      buildConfiguration: "Release"
      repositoryLocation: "Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj"

    steps:
      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk 5.x'
        inputs:
          version: 5.x
          includePreviewVersions: true
      
      - script: |
          dotnet build Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Core
        displayName: "Create nuget packages for Dotmim.Sync.Core"
        continueOnError: true

      - script: |
          dotnet build Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Sqlite  
        displayName: "Create nuget packages for Dotmim.Sync.Sqlite"
        continueOnError: true

      - task: NuGetAuthenticate@0
        displayName: 'NuGet Authenticate'

      - task: NuGetCommand@2
        displayName: "Push to Feed"
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/Dotmim.Sync.Core/*.nupkg;$(Build.ArtifactStagingDirectory)/Dotmim.Sync.Core/*.snupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)
          allowPackageConflicts: true

      - task: NuGetCommand@2
        displayName: "Push to Feed"
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/Dotmim.Sync.Sqlite/*.nupkg;$(Build.ArtifactStagingDirectory)/Dotmim.Sync.Sqlite/*.snupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)
          allowPackageConflicts: true