jobs:
  - job: Release
    displayName: "Release Nuget Packages"

    pool:
      vmImage: "Ubuntu 18.04"

    variables:
      buildConfiguration: "Release"
      artifactName: "release"
      packageID: "Dotmim.Sync.Sqlite"
      repositoryLocation: "Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk 5.x'
        inputs:
          version: 5.x
          includePreviewVersions: true

      - task: NuGetAuthenticate@0
        displayName: 'NuGet Authenticate'

      - task: DotNetCoreCLI@2
        displayName: "Pack the Project"
        inputs:
          command: 'custom'
          custom: 'pack'
          arguments: '$(repositoryLocation) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -v 
          detailed --include-source -p:SymbolPackageFormat=snupkg'
      - task: DotNetCoreCLI@2
        displayName: "Push to Feed"
        inputs:
          command: 'push'
          arguments: '-p:PackageID=$(packageID)'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;$(Build.ArtifactStagingDirectory)/*.snupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)