jobs:
  - job: Release
    displayName: "Release Nuget Packages"

    pool:
      vmImage: "Ubuntu 18.04"

    variables:
      buildConfiguration: "Release"
      artifactName: "release"
      repositoryLocation: "Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj"

    steps:
      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk 5.x'
        inputs:
          version: 5.x
          includePreviewVersions: true

      - task: NuGetAuthenticate@0
        displayName: 'NuGet Authenticate'

      - task: NugetCommand@2
        displayName: "Pack the Project"
        inputs:
          command: pack
          packagesToPack: '$(repositoryLocation)'
          configuration: $(buildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: "Push to Feed"
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)