jobs:
  - job: Release
    displayName: "Release Nuget Packages"

    pool:
      vmImage: "Ubuntu 18.04"

    variables:
      buildConfiguration: "Release"
      artifactName: "release"
      packageID: "Dotmim.Sync.Sqlite"
      repositoryLocation: "Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj"

    steps:
      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk 5.x'
        inputs:
          version: 5.x
          includePreviewVersions: true
      
      - script: |
          dotnet build Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Sqlite  
        displayName: "release nuget Dotmim.Sync.Sqlite"
        continueOnError: true

      - task: NuGetAuthenticate@0
        displayName: 'NuGet Authenticate'

      - task: DotNetCoreCLI@2
        displayName: "Push to Feed"
        inputs:
          command: 'push'
          arguments: '-p:PackageID=$(packageID)'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/Dotmim.Sync/Sqlite/*.nupkg;$(Build.ArtifactStagingDirectory)/Dotmim.Sync/Sqlite/*.snupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(vstsFeed)